version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "kadalis"
      MYSQL_USER: "kadalis_user"
      MYSQL_PASSWORD: "user_password"
    volumes:
      - ./db/mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql_data: {}
